### ISSUE TITLE
Error while running demo program

### ISSUE THREAD

**Issue by yucai2005** [rzzzwilson/pySlipQt#46]
Hi,

I got error while I was trying to run your demo program. Could you please help me out with it? Thanks.

Uncaught exception:
Traceback (most recent call last):
  File "c:\Users\yucai\PycharmProjects\pySlipQt_demo.py", line 2116, in <module>
    ex = PySlipQtDemo()
  File "c:\Users\yucai\PycharmProjects\pySlipQt_demo.py", line 203, in __init__
    self.tile_source = self.tileset_manager.get_tile_source(DefaultTilesetIndex)
  File "c:\Users\yucai\PycharmProjects\pySlipQt_demo.py", line 189, in get_tile_source
    tile_obj = tileset.Tiles()
  File "C:\Python38\lib\site-packages\pySlipQt\gmt_local.py", line 102, in __init__
    (self.num_tiles_x, self.num_tiles_y,
TypeError: cannot unpack non-iterable NoneType object
=======================================================

**Comment by rzzzwilson** [comment]
I can't recreate this problem.  It looks like you are trying to execute pySlipQt_demo.py from within Pycharm.  That's probably not going to work.  The environment within an IDE is not the same as a commandline environment.

I just tested this on MacOS.  I followed the instructions in the https://github.com/rzzzwilson/pySlipQt/ page and did "python setup.py install" in the root of the repository.  You must also install the GMT tiles somewhere.  If I remember, the GMT tiles directory should be unpacked in your home directory.  PySlipQt can use tiles anywhere in your file system, but the demo code assumes ~/gmt_local_tiles.

Once you have done all that you need to use the commandline and CD to the .../pySlipQt/pySlipQt/examples directory and execute the pyslipqt_demo.py code there.  As I said, it works for me on MacOS.

Try all that and if you still have problems send me the pyslipqt.log file that should be in the
.../pySlipQt/pySlipQt/examples directory.

**Comment by rzzzwilson** [comment]
Added code into gmt_local.py to check for correctly set up GMT tiles directory.  Not yet pushed to PyPi, pending testing.

**Comment by rzzzwilson** [comment]
No feedback from complainant and can't recreate here.  Possibly caused by non-existant GMT local tiles.  Code added to make the lack of GMT tiles more obvious.  Closed
