### ISSUE TITLE
How to draw a circle or an arc with pySlipQt

### ISSUE THREAD

**Issue by YDDDDG** [rzzzwilson/pySlipQt#47]
I can draw lines,ponits and polys by using layers in pySlipQt as is shown in demo. The question is ,Does pySlipQt support circle and arc drawing ? If so, please tell me the method; if not, please tell me if there is any alternative to drawing circles and arcs?

**Comment by rzzzwilson** [comment]
No, there is currently no way to draw circles or arcs. You might be able to use images that contain a circle or arc drawn on a transparent background or polygons that draw an outline with 6 or more sides to approximate a circle or an arc.  Depending on what you need the circles for you might even be able to use a point layer with the point colour being mostly transparent.

**Comment by rzzzwilson** [comment]
Closed, will not implement.
